@startjson

title JSON El
{
  "User": {
    "id": "1",
    "login": "el",
    "password": "00000000",
    "age": "20",
    "email": "el@gmail.com",
    "Name": "Danil"
  },
  "HealthCenterEmp": {
      "id":"1",
      "position": "Doctor",
      "age": "60",
      "Name": "Andrii",
      "user id": "2"
  }
}


@endjson
