@startuml
title Activity Diagram sendQuestion()

start
:Consumer sends questions about health;
:The program checks the correctness of the provided data;
if (Are all fields filled in?) then (yes)
    :All fields are filled;
    if (Field values pass validators) then (yes)
        :The field values are correct;
    else (no)
        :The field values are incorrect;
        :The consumer is prompted to re-enter the data;
    endif
else (no)
    :Not all fields are filled;
    :The consumer is prompted to re-enter the data;
endif
stop
@enduml
