@startuml
title Usecases El

left to right direction

actor Consumer

rectangle Software {

    usecase (Analysis of the provided information)
    usecase (Receiving problem reports)

   Consumer -- (Analysis of the provided information)
   (Analysis of the provided information) .> (Receiving problem reports) : include
}
@enduml
