@startuml

title Activity Diagram sendQuestion()

start
:Користувач надсилає питання  з приводу здоров'я;
:Програма перевіряє коректність наданих даних; 
if (Чи всі поля заповнені?) then (yes)
   :Всі поля заповнені;
   if (Значення полів проходять валідатори) then (yes)
       :Значення полів правильні;
   else (no)
       :Значення полів неправильні;
       :Користувачеві пропонується повторно ввести дані;
   endif
else (no)
   :Не всі поля заповнені;
   :Користувачеві пропонується повторно ввести дані;
endif
stop

@enduml
